let stores = [
  {
    id: "1",
    name: "ANGELES 1",
    phoneNumber: "6677-442-578",
    coordinates: {
      latitude: 24.84369,
      longitude: -107.35826,
    },
    address: {
      streetAddressLine1: "BOULEVARD CALIFORNIA #3245INT 1",
      streetAddressLine2: "FRACC. LOS ANGELES",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "80014",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "09:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "2",
    name: "ANGOSTURA",
    phoneNumber: "6971-081-175",
    coordinates: {
      latitude: 25.36469,
      longitude: -108.16034,
    },
    address: {
      streetAddressLine1: "CALLE GABRIEL LEYVA S/N",
      streetAddressLine2: "ANGOSTURA, SINALOA",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "81600",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "3",
    name: "CHULAVISTA",
    phoneNumber: "6677-451-763",
    coordinates: {
      latitude: 24.75394,
      longitude: -107.41618,
    },
    address: {
      streetAddressLine1: "BLVD. EJERCITO DE OCCIDENTE # 5797 LOCAL 1",
      streetAddressLine2: "FRACC. PRADOS DEL SOL",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "80197",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "4",
    name: "EL DORADO",
    phoneNumber: "6677-242-378",
    coordinates: {
      latitude: 24.32113,
      longitude: -107.36463,
    },
    address: {
      streetAddressLine1: "INDEPENDENCIA S/N",
      streetAddressLine2: "CENTRO, EL DORADO, SIN",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "80450",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "5",
    name: "GUADALUPE VICTORIA",
    phoneNumber: "6677-495-639",
    coordinates: {
      latitude: 24.7935,
      longitude: -107.35822,
    },
    address: {
      streetAddressLine1: "AV. MANUEL ESTRADA #3707 B",
      streetAddressLine2: "GUADALUPE VICTORIA",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "80240",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "6",
    name: "LA CRUZ ELOTA",
    phoneNumber: "6969-611-645",
    coordinates: {
      latitude: 23.91522,
      longitude: -106.89333,
    },
    address: {
      streetAddressLine1: "GABRIEL LEYVA SOLANO S/N",
      streetAddressLine2: "CENTRO, LA CRUZ DE ELOTA, SIN.",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "82700",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "7",
    name: "NAVOLATO",
    phoneNumber: "6727-210746",
    coordinates: {
      latitude: 24.76726,
      longitude: -107.69872,
    },
    address: {
      streetAddressLine1: "ALMADA #116",
      streetAddressLine2: "CENTRO , NAVOLATO, SIN.",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "80320",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 07:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "8",
    name: "PERICOS",
    phoneNumber: "6971-080455",
    coordinates: {
      latitude: 25.08205,
      longitude: -107.69812,
    },
    address: {
      streetAddressLine1: "ANGEL FLORES #17",
      streetAddressLine2: "PERICOS, MOCORITO, SIN.",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "80950",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "9",
    name: "VILLA JUAREZ",
    phoneNumber: "6727-286436",
    coordinates: {
      latitude: 24.65943,
      longitude: -107.53834,
    },
    address: {
      streetAddressLine1: "CALZADA BENITO JUAREZ S/N LOCAL B",
      streetAddressLine2: "4 DE MARZO, VILLA JUAREZ, NAV",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "80379",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 08:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "10",
    name: "STANZA TOSCANA",
    phoneNumber: "6674-454004",
    coordinates: {
      latitude: 24.81022,
      longitude: -107.46357,
    },
    address: {
      streetAddressLine1: "AV. ALVARO DEL PORTILLO",
      streetAddressLine2: "STANZA TOSCANA",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "80050",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "11",
    name: "ALTURAS DEL SUR",
    phoneNumber: "6675-996697",
    coordinates: {
      latitude: 24.76241,
      longitude: -107.35726,
    },
    address: {
      streetAddressLine1: "BLVD. JUAN LEY FONG #3529 OTE. LOCAL 1 Y 2",
      streetAddressLine2: "ALTURAS DEL SUR",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "80295",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
  {
    id: "12",
    name: "HORIZONTES",
    phoneNumber: "6678104296",
    coordinates: {
      latitude: 24.81598,
      longitude: -107.43561,
    },
    address: {
      streetAddressLine1: "BLVD. MARIO LÓPEZ VALDEZ 1535",
      streetAddressLine2: "LA CONQUISTA",
      streetAddressLine3: null,
      city: null,
      countrySubdivisionCode: null,
      countryCode: null,
      postalCode: "80058",
    },
    schedule: [
      {
        dayName: "Lunes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Martes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Miércoles",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Jueves",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Viernes",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sábado",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Domingo",
        hours: "08:00 AM a 09:00 PM",
        open: true,
        holiday: "",
      },
    ],
  },
];
